export const category = {
  DEVELOPMENT: "19",
  IDLE: "21",
  MEETING_CLIENT: "23",
  MEETING_INTERNAL: "24",
  ADMINISTRATIVE: "18",
}

export const taskDescription = {
  FEATURE_DEVELOPMENT: "783",
  DAILY_MEETING: "909",
  NO_ASSIGNED_TASKS: "880",
  OTHER_MEETINGS: "1013",
  CLIENT_MEETING: "908",
  TEAM_BUILDING: "939",
  REGISTERING_TIMETRACKER: "4417",
}